project_id: '454660'
api_token: 'REPLACE_THIS_WITH_API_TOKEN'
preserve_hierarchy: true
files: [
    # https://support.crowdin.com/configuration-file/#language-mapping の通りにやって簡体中文の`two_letters_code`を`zh-CN`にせよ。
    # JSON translation files
    {
      source: '/i18n/ja/**/*',
      translation: '/i18n/%two_letters_code%/**/%original_file_name%',
    },
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
    },
    # Blog Markdown files
    {
      source: '/blog/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%',
    },
  ]
