name: Auto Comment
on:
  pull_request_target:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpenedReactions: 'hooray, +1, eyes'
          pullRequestOpened: >
            👋 @{{ author }}
            サイトに反映されるまで3分ほどかかります。緑色になるまで、しばらくお待ちください！
          pullRequestClosed: >
            👋 @{{ author }}
            もし`✅ Preview: Failed` / `vercel bot had a problem deploying to Preview` と出ている場合は反映できていないので、**記事内のHTMLの構文がJSXとして有効かどうか**ご確認ください。
