name: Auto Comment
on:
  pull_request_target:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpenedReactions: 'hooray, +1, eyes'
          pullRequestOpened: >
            👋 @{{ author }}
            プルリク受け取りました！ビルド成功した後も、**本体サイトの更新にはもう三分ほど時間がかかります。**もし`Some checks were not successful` と出ている場合は反映できていないので、**記事内のHTMLの構文がJSXとして有効かどうか**ご確認ください。
          pullRequestClosed: >
            👋 @{{ author }}
            PRはクローズされました!
