name: Auto Comment
on:
  issues:
  pull_request:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            👋 @{{ author }}

            issue投稿ありがとうな！確認にちょっと時間かかるかもわからんから、ちょっと待っててな。ほな！

          pullRequestOpened: >
            👋 @{{ author }}

            プルリクエストありがとうやで。確認にちょっと時間かかるかもわからんから、ちょっと待っててな。ほな！
