name: Discord Message Notify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#ff3f00"
          username: "ナポコムMD更新通知くん"
          args: mainブランチで ${{ github.event_name }} がトリガーされました。サイトを更新します。
