name: Discord Message Notify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: '#2687e8'
          username: 'Asobinon 통지'
          args: main 분기에 ${{github.event_name}} 이 트리거되었습니다. 사이트를 업데이트하고 있습니다. 1 분 정도 시간이 걸리므로 잠시 기다려주십시오.
